/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef IpcManageServer_CONSTANTS_H
#define IpcManageServer_CONSTANTS_H

#include "IpcManageServer_types.h"

namespace ipcms {

class IpcManageServerConstants {
 public:
  IpcManageServerConstants();

};

extern const IpcManageServerConstants g_IpcManageServer_constants;

} // namespace

#endif
