/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "IpcManageServer_constants.h"

namespace ipcms {

const IpcManageServerConstants g_IpcManageServer_constants;

IpcManageServerConstants::IpcManageServerConstants() {
}

} // namespace

