/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef MediaManagerStruct_CONSTANTS_H
#define MediaManagerStruct_CONSTANTS_H

#include "MediaManagerStruct_types.h"

namespace ipcms {

class MediaManagerStructConstants {
 public:
  MediaManagerStructConstants();

};

extern const MediaManagerStructConstants g_MediaManagerStruct_constants;

} // namespace

#endif
