/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef OperateStruct_CONSTANTS_H
#define OperateStruct_CONSTANTS_H

#include "OperateStruct_types.h"

namespace ipcms {

class OperateStructConstants {
 public:
  OperateStructConstants();

};

extern const OperateStructConstants g_OperateStruct_constants;

} // namespace

#endif
