/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "ReturnStruct_constants.h"

namespace ipcms {

const ReturnStructConstants g_ReturnStruct_constants;

ReturnStructConstants::ReturnStructConstants() {
}

} // namespace

