/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "ReturnStruct_types.h"

#include <algorithm>
#include <ostream>

#include <thrift/TToString.h>

namespace ipcms {


UserLoginReturnStruct::~UserLoginReturnStruct() throw() {
}


void UserLoginReturnStruct::__set_ErrorNum(const int8_t val) {
  this->ErrorNum = val;
}

void UserLoginReturnStruct::__set_UserID(const std::string& val) {
  this->UserID = val;
}

void UserLoginReturnStruct::__set_SessionID(const std::string& val) {
  this->SessionID = val;
}

const char* UserLoginReturnStruct::ascii_fingerprint = "15B1A498AD6EEF5345D267BE66D87AFD";
const uint8_t UserLoginReturnStruct::binary_fingerprint[16] = {0x15,0xB1,0xA4,0x98,0xAD,0x6E,0xEF,0x53,0x45,0xD2,0x67,0xBE,0x66,0xD8,0x7A,0xFD};

uint32_t UserLoginReturnStruct::read(::apache::thrift::protocol::TProtocol* iprot) {

  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;


  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_BYTE) {
          xfer += iprot->readByte(this->ErrorNum);
          this->__isset.ErrorNum = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 2:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->UserID);
          this->__isset.UserID = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 3:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->SessionID);
          this->__isset.SessionID = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  return xfer;
}

uint32_t UserLoginReturnStruct::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  oprot->incrementRecursionDepth();
  xfer += oprot->writeStructBegin("UserLoginReturnStruct");

  xfer += oprot->writeFieldBegin("ErrorNum", ::apache::thrift::protocol::T_BYTE, 1);
  xfer += oprot->writeByte(this->ErrorNum);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("UserID", ::apache::thrift::protocol::T_STRING, 2);
  xfer += oprot->writeString(this->UserID);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("SessionID", ::apache::thrift::protocol::T_STRING, 3);
  xfer += oprot->writeString(this->SessionID);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  oprot->decrementRecursionDepth();
  return xfer;
}

void swap(UserLoginReturnStruct &a, UserLoginReturnStruct &b) {
  using ::std::swap;
  swap(a.ErrorNum, b.ErrorNum);
  swap(a.UserID, b.UserID);
  swap(a.SessionID, b.SessionID);
  swap(a.__isset, b.__isset);
}

UserLoginReturnStruct::UserLoginReturnStruct(const UserLoginReturnStruct& other0) {
  ErrorNum = other0.ErrorNum;
  UserID = other0.UserID;
  SessionID = other0.SessionID;
  __isset = other0.__isset;
}
UserLoginReturnStruct& UserLoginReturnStruct::operator=(const UserLoginReturnStruct& other1) {
  ErrorNum = other1.ErrorNum;
  UserID = other1.UserID;
  SessionID = other1.SessionID;
  __isset = other1.__isset;
  return *this;
}
std::ostream& operator<<(std::ostream& out, const UserLoginReturnStruct& obj) {
  using apache::thrift::to_string;
  out << "UserLoginReturnStruct(";
  out << "ErrorNum=" << to_string(obj.ErrorNum);
  out << ", " << "UserID=" << to_string(obj.UserID);
  out << ", " << "SessionID=" << to_string(obj.SessionID);
  out << ")";
  return out;
}


ResourceInfoReturnStruct::~ResourceInfoReturnStruct() throw() {
}


void ResourceInfoReturnStruct::__set_length(const int64_t val) {
  this->length = val;
}

void ResourceInfoReturnStruct::__set_hResource(const int64_t val) {
  this->hResource = val;
}

void ResourceInfoReturnStruct::__set_hasPLZ(const bool val) {
  this->hasPLZ = val;
}

void ResourceInfoReturnStruct::__set_timeStart(const int64_t val) {
  this->timeStart = val;
}

void ResourceInfoReturnStruct::__set_timeEnd(const int64_t val) {
  this->timeEnd = val;
}

void ResourceInfoReturnStruct::__set_nameLength(const int64_t val) {
  this->nameLength = val;
}

const char* ResourceInfoReturnStruct::ascii_fingerprint = "DC7B5F9F55550684275623CB722904E8";
const uint8_t ResourceInfoReturnStruct::binary_fingerprint[16] = {0xDC,0x7B,0x5F,0x9F,0x55,0x55,0x06,0x84,0x27,0x56,0x23,0xCB,0x72,0x29,0x04,0xE8};

uint32_t ResourceInfoReturnStruct::read(::apache::thrift::protocol::TProtocol* iprot) {

  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;


  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_I64) {
          xfer += iprot->readI64(this->length);
          this->__isset.length = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 2:
        if (ftype == ::apache::thrift::protocol::T_I64) {
          xfer += iprot->readI64(this->hResource);
          this->__isset.hResource = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 3:
        if (ftype == ::apache::thrift::protocol::T_BOOL) {
          xfer += iprot->readBool(this->hasPLZ);
          this->__isset.hasPLZ = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 4:
        if (ftype == ::apache::thrift::protocol::T_I64) {
          xfer += iprot->readI64(this->timeStart);
          this->__isset.timeStart = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 5:
        if (ftype == ::apache::thrift::protocol::T_I64) {
          xfer += iprot->readI64(this->timeEnd);
          this->__isset.timeEnd = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 6:
        if (ftype == ::apache::thrift::protocol::T_I64) {
          xfer += iprot->readI64(this->nameLength);
          this->__isset.nameLength = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  return xfer;
}

uint32_t ResourceInfoReturnStruct::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  oprot->incrementRecursionDepth();
  xfer += oprot->writeStructBegin("ResourceInfoReturnStruct");

  xfer += oprot->writeFieldBegin("length", ::apache::thrift::protocol::T_I64, 1);
  xfer += oprot->writeI64(this->length);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("hResource", ::apache::thrift::protocol::T_I64, 2);
  xfer += oprot->writeI64(this->hResource);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("hasPLZ", ::apache::thrift::protocol::T_BOOL, 3);
  xfer += oprot->writeBool(this->hasPLZ);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("timeStart", ::apache::thrift::protocol::T_I64, 4);
  xfer += oprot->writeI64(this->timeStart);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("timeEnd", ::apache::thrift::protocol::T_I64, 5);
  xfer += oprot->writeI64(this->timeEnd);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("nameLength", ::apache::thrift::protocol::T_I64, 6);
  xfer += oprot->writeI64(this->nameLength);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  oprot->decrementRecursionDepth();
  return xfer;
}

void swap(ResourceInfoReturnStruct &a, ResourceInfoReturnStruct &b) {
  using ::std::swap;
  swap(a.length, b.length);
  swap(a.hResource, b.hResource);
  swap(a.hasPLZ, b.hasPLZ);
  swap(a.timeStart, b.timeStart);
  swap(a.timeEnd, b.timeEnd);
  swap(a.nameLength, b.nameLength);
  swap(a.__isset, b.__isset);
}

ResourceInfoReturnStruct::ResourceInfoReturnStruct(const ResourceInfoReturnStruct& other2) {
  length = other2.length;
  hResource = other2.hResource;
  hasPLZ = other2.hasPLZ;
  timeStart = other2.timeStart;
  timeEnd = other2.timeEnd;
  nameLength = other2.nameLength;
  __isset = other2.__isset;
}
ResourceInfoReturnStruct& ResourceInfoReturnStruct::operator=(const ResourceInfoReturnStruct& other3) {
  length = other3.length;
  hResource = other3.hResource;
  hasPLZ = other3.hasPLZ;
  timeStart = other3.timeStart;
  timeEnd = other3.timeEnd;
  nameLength = other3.nameLength;
  __isset = other3.__isset;
  return *this;
}
std::ostream& operator<<(std::ostream& out, const ResourceInfoReturnStruct& obj) {
  using apache::thrift::to_string;
  out << "ResourceInfoReturnStruct(";
  out << "length=" << to_string(obj.length);
  out << ", " << "hResource=" << to_string(obj.hResource);
  out << ", " << "hasPLZ=" << to_string(obj.hasPLZ);
  out << ", " << "timeStart=" << to_string(obj.timeStart);
  out << ", " << "timeEnd=" << to_string(obj.timeEnd);
  out << ", " << "nameLength=" << to_string(obj.nameLength);
  out << ")";
  return out;
}


ApplyPTZControlReturnStruct::~ApplyPTZControlReturnStruct() throw() {
}


void ApplyPTZControlReturnStruct::__set_hPLZ(const int64_t val) {
  this->hPLZ = val;
}

void ApplyPTZControlReturnStruct::__set_result(const int64_t val) {
  this->result = val;
}

void ApplyPTZControlReturnStruct::__set_userName(const std::string& val) {
  this->userName = val;
}

const char* ApplyPTZControlReturnStruct::ascii_fingerprint = "6B0CD68886A371B59CE1B9EDCF067801";
const uint8_t ApplyPTZControlReturnStruct::binary_fingerprint[16] = {0x6B,0x0C,0xD6,0x88,0x86,0xA3,0x71,0xB5,0x9C,0xE1,0xB9,0xED,0xCF,0x06,0x78,0x01};

uint32_t ApplyPTZControlReturnStruct::read(::apache::thrift::protocol::TProtocol* iprot) {

  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;


  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_I64) {
          xfer += iprot->readI64(this->hPLZ);
          this->__isset.hPLZ = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 2:
        if (ftype == ::apache::thrift::protocol::T_I64) {
          xfer += iprot->readI64(this->result);
          this->__isset.result = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 3:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->userName);
          this->__isset.userName = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  return xfer;
}

uint32_t ApplyPTZControlReturnStruct::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  oprot->incrementRecursionDepth();
  xfer += oprot->writeStructBegin("ApplyPTZControlReturnStruct");

  xfer += oprot->writeFieldBegin("hPLZ", ::apache::thrift::protocol::T_I64, 1);
  xfer += oprot->writeI64(this->hPLZ);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("result", ::apache::thrift::protocol::T_I64, 2);
  xfer += oprot->writeI64(this->result);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("userName", ::apache::thrift::protocol::T_STRING, 3);
  xfer += oprot->writeString(this->userName);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  oprot->decrementRecursionDepth();
  return xfer;
}

void swap(ApplyPTZControlReturnStruct &a, ApplyPTZControlReturnStruct &b) {
  using ::std::swap;
  swap(a.hPLZ, b.hPLZ);
  swap(a.result, b.result);
  swap(a.userName, b.userName);
  swap(a.__isset, b.__isset);
}

ApplyPTZControlReturnStruct::ApplyPTZControlReturnStruct(const ApplyPTZControlReturnStruct& other4) {
  hPLZ = other4.hPLZ;
  result = other4.result;
  userName = other4.userName;
  __isset = other4.__isset;
}
ApplyPTZControlReturnStruct& ApplyPTZControlReturnStruct::operator=(const ApplyPTZControlReturnStruct& other5) {
  hPLZ = other5.hPLZ;
  result = other5.result;
  userName = other5.userName;
  __isset = other5.__isset;
  return *this;
}
std::ostream& operator<<(std::ostream& out, const ApplyPTZControlReturnStruct& obj) {
  using apache::thrift::to_string;
  out << "ApplyPTZControlReturnStruct(";
  out << "hPLZ=" << to_string(obj.hPLZ);
  out << ", " << "result=" << to_string(obj.result);
  out << ", " << "userName=" << to_string(obj.userName);
  out << ")";
  return out;
}

} // namespace
