/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef ReturnStruct_CONSTANTS_H
#define ReturnStruct_CONSTANTS_H

#include "ReturnStruct_types.h"

namespace ipcms {

class ReturnStructConstants {
 public:
  ReturnStructConstants();

};

extern const ReturnStructConstants g_ReturnStruct_constants;

} // namespace

#endif
