/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef ReturnStruct_TYPES_H
#define ReturnStruct_TYPES_H

#include <iosfwd>

#include <thrift/Thrift.h>
#include <thrift/TApplicationException.h>
#include <thrift/protocol/TProtocol.h>
#include <thrift/transport/TTransport.h>

#include <thrift/cxxfunctional.h>


namespace ipcms {

struct ResourceType {
  enum type {
    ResourceTypeALL = 0,
    ResourceTypeReplay = 1,
    ResourceTypeIPC = 2
  };
};

extern const std::map<int, const char*> _ResourceType_VALUES_TO_NAMES;

struct PTZControlReturnType {
  enum type {
    PTZControlReturnTypeInvalidHandle = 0,
    PTZControlReturnTypeSuccess = 1,
    PTZControlReturnTypeError = 2
  };
};

extern const std::map<int, const char*> _PTZControlReturnType_VALUES_TO_NAMES;

class UserLoginReturnStruct;

class ResourceInfoReturnStruct;

class RequestPTZControlReturnStruct;

class PTZControlReturnStruct;

typedef struct _UserLoginReturnStruct__isset {
  _UserLoginReturnStruct__isset() : ErrorNum(false), UserID(false), SessionID(false) {}
  bool ErrorNum :1;
  bool UserID :1;
  bool SessionID :1;
} _UserLoginReturnStruct__isset;

class UserLoginReturnStruct {
 public:

  static const char* ascii_fingerprint; // = "15B1A498AD6EEF5345D267BE66D87AFD";
  static const uint8_t binary_fingerprint[16]; // = {0x15,0xB1,0xA4,0x98,0xAD,0x6E,0xEF,0x53,0x45,0xD2,0x67,0xBE,0x66,0xD8,0x7A,0xFD};

  UserLoginReturnStruct(const UserLoginReturnStruct&);
  UserLoginReturnStruct& operator=(const UserLoginReturnStruct&);
  UserLoginReturnStruct() : ErrorNum(0), UserID(), SessionID() {
  }

  virtual ~UserLoginReturnStruct() throw();
  int8_t ErrorNum;
  std::string UserID;
  std::string SessionID;

  _UserLoginReturnStruct__isset __isset;

  void __set_ErrorNum(const int8_t val);

  void __set_UserID(const std::string& val);

  void __set_SessionID(const std::string& val);

  bool operator == (const UserLoginReturnStruct & rhs) const
  {
    if (!(ErrorNum == rhs.ErrorNum))
      return false;
    if (!(UserID == rhs.UserID))
      return false;
    if (!(SessionID == rhs.SessionID))
      return false;
    return true;
  }
  bool operator != (const UserLoginReturnStruct &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const UserLoginReturnStruct & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  friend std::ostream& operator<<(std::ostream& out, const UserLoginReturnStruct& obj);
};

void swap(UserLoginReturnStruct &a, UserLoginReturnStruct &b);

typedef struct _ResourceInfoReturnStruct__isset {
  _ResourceInfoReturnStruct__isset() : resourceType(false), hResource(false), hasPLZ(false), timeStart(false), timeEnd(false), nameLength(false) {}
  bool resourceType :1;
  bool hResource :1;
  bool hasPLZ :1;
  bool timeStart :1;
  bool timeEnd :1;
  bool nameLength :1;
} _ResourceInfoReturnStruct__isset;

class ResourceInfoReturnStruct {
 public:

  static const char* ascii_fingerprint; // = "AC9C4895E6FDB4C04F2C42875F33A426";
  static const uint8_t binary_fingerprint[16]; // = {0xAC,0x9C,0x48,0x95,0xE6,0xFD,0xB4,0xC0,0x4F,0x2C,0x42,0x87,0x5F,0x33,0xA4,0x26};

  ResourceInfoReturnStruct(const ResourceInfoReturnStruct&);
  ResourceInfoReturnStruct& operator=(const ResourceInfoReturnStruct&);
  ResourceInfoReturnStruct() : resourceType((ResourceType::type)0), hResource(0), hasPLZ(0), timeStart(0), timeEnd(0), nameLength(0) {
  }

  virtual ~ResourceInfoReturnStruct() throw();
  ResourceType::type resourceType;
  int64_t hResource;
  bool hasPLZ;
  int64_t timeStart;
  int64_t timeEnd;
  int64_t nameLength;

  _ResourceInfoReturnStruct__isset __isset;

  void __set_resourceType(const ResourceType::type val);

  void __set_hResource(const int64_t val);

  void __set_hasPLZ(const bool val);

  void __set_timeStart(const int64_t val);

  void __set_timeEnd(const int64_t val);

  void __set_nameLength(const int64_t val);

  bool operator == (const ResourceInfoReturnStruct & rhs) const
  {
    if (__isset.resourceType != rhs.__isset.resourceType)
      return false;
    else if (__isset.resourceType && !(resourceType == rhs.resourceType))
      return false;
    if (!(hResource == rhs.hResource))
      return false;
    if (!(hasPLZ == rhs.hasPLZ))
      return false;
    if (!(timeStart == rhs.timeStart))
      return false;
    if (!(timeEnd == rhs.timeEnd))
      return false;
    if (!(nameLength == rhs.nameLength))
      return false;
    return true;
  }
  bool operator != (const ResourceInfoReturnStruct &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ResourceInfoReturnStruct & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  friend std::ostream& operator<<(std::ostream& out, const ResourceInfoReturnStruct& obj);
};

void swap(ResourceInfoReturnStruct &a, ResourceInfoReturnStruct &b);

typedef struct _RequestPTZControlReturnStruct__isset {
  _RequestPTZControlReturnStruct__isset() : hPTZ(false), result(false), userName(false) {}
  bool hPTZ :1;
  bool result :1;
  bool userName :1;
} _RequestPTZControlReturnStruct__isset;

class RequestPTZControlReturnStruct {
 public:

  static const char* ascii_fingerprint; // = "6B0CD68886A371B59CE1B9EDCF067801";
  static const uint8_t binary_fingerprint[16]; // = {0x6B,0x0C,0xD6,0x88,0x86,0xA3,0x71,0xB5,0x9C,0xE1,0xB9,0xED,0xCF,0x06,0x78,0x01};

  RequestPTZControlReturnStruct(const RequestPTZControlReturnStruct&);
  RequestPTZControlReturnStruct& operator=(const RequestPTZControlReturnStruct&);
  RequestPTZControlReturnStruct() : hPTZ(0), result(0), userName() {
  }

  virtual ~RequestPTZControlReturnStruct() throw();
  int64_t hPTZ;
  int64_t result;
  std::string userName;

  _RequestPTZControlReturnStruct__isset __isset;

  void __set_hPTZ(const int64_t val);

  void __set_result(const int64_t val);

  void __set_userName(const std::string& val);

  bool operator == (const RequestPTZControlReturnStruct & rhs) const
  {
    if (!(hPTZ == rhs.hPTZ))
      return false;
    if (!(result == rhs.result))
      return false;
    if (!(userName == rhs.userName))
      return false;
    return true;
  }
  bool operator != (const RequestPTZControlReturnStruct &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const RequestPTZControlReturnStruct & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  friend std::ostream& operator<<(std::ostream& out, const RequestPTZControlReturnStruct& obj);
};

void swap(RequestPTZControlReturnStruct &a, RequestPTZControlReturnStruct &b);

typedef struct _PTZControlReturnStruct__isset {
  _PTZControlReturnStruct__isset() : result(false) {}
  bool result :1;
} _PTZControlReturnStruct__isset;

class PTZControlReturnStruct {
 public:

  static const char* ascii_fingerprint; // = "8C1740BBF54FD399631A4549952454DB";
  static const uint8_t binary_fingerprint[16]; // = {0x8C,0x17,0x40,0xBB,0xF5,0x4F,0xD3,0x99,0x63,0x1A,0x45,0x49,0x95,0x24,0x54,0xDB};

  PTZControlReturnStruct(const PTZControlReturnStruct&);
  PTZControlReturnStruct& operator=(const PTZControlReturnStruct&);
  PTZControlReturnStruct() : result((PTZControlReturnType::type)0) {
  }

  virtual ~PTZControlReturnStruct() throw();
  PTZControlReturnType::type result;

  _PTZControlReturnStruct__isset __isset;

  void __set_result(const PTZControlReturnType::type val);

  bool operator == (const PTZControlReturnStruct & rhs) const
  {
    if (__isset.result != rhs.__isset.result)
      return false;
    else if (__isset.result && !(result == rhs.result))
      return false;
    return true;
  }
  bool operator != (const PTZControlReturnStruct &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const PTZControlReturnStruct & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  friend std::ostream& operator<<(std::ostream& out, const PTZControlReturnStruct& obj);
};

void swap(PTZControlReturnStruct &a, PTZControlReturnStruct &b);

} // namespace

#endif
